<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO7xsxoy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO7xsxoy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO7xsxoy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO7xsxoy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO7xsxoy\App_KernelDevDebugContainer([
    'container.build_hash' => 'O7xsxoy',
    'container.build_id' => 'd155a2de',
    'container.build_time' => 1713711975,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO7xsxoy');
