<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFVpaD7f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFVpaD7f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFVpaD7f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFVpaD7f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFVpaD7f\App_KernelDevDebugContainer([
    'container.build_hash' => 'FVpaD7f',
    'container.build_id' => 'fee341cd',
    'container.build_time' => 1713768947,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFVpaD7f');
